### ISSUE TITLE
Kunde21/gitea-arm Error message in log after update to v1.13.3

### ISSUE THREAD

**Issue by brtwrst** [Kunde21/raspberry-dev#8]
After updating the image to v1.13.3 via docker pull the container produces the following log messages in `docker logs` (very spammy - once per second)
```
s6-supervise gitea: warning: can't happen: timeout while the service is up!
s6-supervise openssh: warning: can't happen: timeout while the service is up!
```

RPI4 - RaspberryOS 32bit

**Comment by brtwrst** [comment]
After reverting to 1.13.2 the messages no longer appear.

**Comment by brtwrst** [comment]
Problem still appears in v1.13.4

I tried running the container without any data in the docker volume ("fresh install") but even then the errors start immediately.

**Comment by dotWee** [comment]
Had the same problems after switching the image from `v1.13.1` to `v1.13.4`. I've also tried using `v1.13.4-armv7` & (the current current) `latest` without luck.

Using the older image `v1.13.2` throws no errors.

**Comment by Kunde21** [comment]
After wandering down the wrong path for a while, I finally tracked down the issue to alpine 3.13.  https://gitlab.alpinelinux.org/alpine/aports/-/issues/12346

v1.13.3 and v1.13.4 were built with alpine 3.13, meaning that's why v1.13.2 wasn't affected.  I'm re-building these two versions with alpine 3.12 (until the fix is merged to 3.13) so please pull the new image before deploying.

Thank you for raising this issue.  Let me know if you run into any problems.

**Comment by brtwrst** [comment]
can confirm that the error is not appearing any more with :latest

thank you for your work

**Comment by dotWee** [comment]
Works flawlessly. Thanks for the quick fix!
